     CREATE TABLE [DevPrimeStream] (                                 
          [Dictionary] nvarchar(max) NULL,                          
          [SagaId] uniqueidentifier NULL,                           
          [Id] uniqueidentifier NOT NULL,                           
          [CorrelationId] uniqueidentifier NULL,      
          [TraceId] uniqueidentifier NULL,  
          [AppId] uniqueidentifier NULL,                        
          [AppName] nvarchar(255) NULL,  
          [TenantUserID] nvarchar(255) NULL, 
          [TenantID] nvarchar(255) NULL,
          [Version] int NULL,                                       
          [Name] nvarchar(255) NULL,                                
          [CreationDate] datetime2 NOT NULL,                                
          [Payload] nvarchar(max) NULL,                             
          [ResponseQueue] nvarchar(255) NULL,                       
          [Queue] nvarchar(255) NULL,       
          [StreamAlias] nvarchar(255) NULL,                               
          [Read] datetime2 NOT NULL,                                
          [ProcessId] uniqueidentifier NULL,                    
          CONSTRAINT [PK_DevPrimeEvent] PRIMARY KEY ([Id])             
          );    